baseURL = "https://samek.fyi"
title = "samek.fyi"
languageCode = "en-us"

[permalinks]
  posts = "/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/about-me/"
    weight = 1
  [[menu.main]]
    name = "AI Benchmarks"
    url = "/benchmarks/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 3
